name: FTP Deploy

on:
  push:
    branches:
      - main
      - production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Install PHP Dependencies (Production)
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Build Assets
        run: npm run build

      - name: Publish Ziggy Configuration
        run: php artisan ziggy:generate

      - name: Optimize Laravel Application
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Remove Development Files
        run: |
          rm -rf node_modules
          rm -rf tests
          rm -f .env.example .env.testing
          rm -f package.json package-lock.json
          rm -f composer.json composer.lock
          rm -f phpunit.xml vite.config.ts tsconfig.json eslint.config.js
          rm -f .editorconfig .styleci.yml README.md
          rm -rf .git .github

      - name: Create ZIP File
        run: |
          mkdir deploy
          zip -r deploy/archive.zip ./* -x ".git/*" ".github/*" "node_modules/*" ".env" "storage/*"
          
      - name: Upload ZIP File via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            .env.testing
            storage/logs/*.log
            storage/framework/cache/data/**
            storage/framework/sessions/**
            storage/framework/views/**
            bootstrap/cache/*.php
        
      - name: Trigger Unzipper Script
        run: |
          curl -X GET "${{secrets.APP_URL}}/unzipper.php"

      - name: Run Migrations
        run: |
          curl -X GET "${{secrets.APP_URL}}/run-migrations/${{ secrets.MIGRATION_KEY }}"

      - name: Clear Laravel Caches
        run: |
          curl -X GET "${{secrets.APP_URL}}/clear-caches/${{ secrets.MIGRATION_KEY }}"

      - name: Deployment Success Notification
        if: success()
        run: echo "🚀 Deployment completed successfully to ${{ secrets.FTP_SERVER }}!"

      - name: Deployment Failure Notification  
        if: failure()
        run: |
          echo "❌ Deployment failed!"
          exit 1
